In [1]:
import pandas as pd

df = pd.read_csv('/content/Company_Financials_2021_2023.csv')
df.head()

,Company,Year,Total Revenue (USD Millions),Net Income (USD Millions),Total Assets (USD Millions),Total Liabilities (USD Millions),Operating Cash Flow (USD Millions)
0,Microsoft,2023,211915,72361,411981,198298,89034
1,Microsoft,2022,198270,72738,364840,191791,83383
2,Microsoft,2021,168088,61271,333779,183007,76737
3,Tesla,2023,96773,14997,93853,40553,13264
4,Tesla,2022,81462,12556,82338,35466,14724

In [2]:
# Calculate YoY percentage growth for revenue and net income
df['Revenue Growth (%)'] = df.groupby('Company')['Total Revenue (USD Millions)'].pct_change() * 100
df['Net Income Growth (%)'] = df.groupby('Company')['Net Income (USD Millions)'].pct_change() * 100
df['Assets Growth (%)'] = df.groupby('Company')['Total Assets (USD Millions)'].pct_change() * 100
df['Liabilities Growth (%)'] = df.groupby('Company')['Total Liabilities (USD Millions)'].pct_change() * 100
df['Cash Flow Growth (%)'] = df.groupby('Company')['Operating Cash Flow (USD Millions)'].pct_change() * 100

# Display the updated DataFrame
df

,Company,Year,Total Revenue (USD Millions),Net Income (USD Millions),Total Assets (USD Millions),Total Liabilities (USD Millions),Operating Cash Flow (USD Millions),Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Liabilities Growth (%),Cash Flow Growth (%)
0,Microsoft,2023,211915,72361,411981,198298,89034,NaN,NaN,NaN,NaN,NaN
1,Microsoft,2022,198270,72738,364840,191791,83383,-6.438902,0.520999,-11.442518,-3.281425,-6.347014
2,Microsoft,2021,168088,61271,333779,183007,76737,-15.222676,-15.764800,-8.513595,-4.579986,-7.970450
3,Tesla,2023,96773,14997,93853,40553,13264,NaN,NaN,NaN,NaN,NaN
4,Tesla,2022,81462,12556,82338,35466,14724,-15.821562,-16.276589,-12.269187,-12.544078,11.007238
5,Tesla,2021,53823,5519,62131,30548,11497,-33.928703,-56.044919,-24.541524,-13.866802,-21.916599
6,Apple,2023,383285,96995,352583,290437,110543,NaN,NaN,NaN,NaN,NaN
7,Apple,2022,394328,99803,352755,302083,122151,2.881146,2.894995,0.048783,4.009820,10.500891
8,Apple,2021,365817,94680,351002,287912,104038,-7.230275,-5.133112,-0.496945,-4.691095,-14.828368

### 🔍 Summary of Financial Trends (2021–2023)

- **Apple** showed steady growth in revenue until 2022, followed by a slight decline in 2023. Net income remained strong but also declined slightly in the latest year.
- **Tesla** experienced strong revenue and net income growth across all years, indicating rapid expansion and improving profitability.
- **Microsoft** maintained stable revenue growth and strong net income. Operating cash flow steadily increased, indicating healthy cash generation.

Overall, all three companies show strong financials, with Tesla growing fastest and Apple maintaining the highest income and cash flows.